#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.orig 0 > /dev/null 2>&1
runApplication blockMesh
#runApplication setSet -batch createObstacle.setSet
runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch walls

# initialize field and set refinement repeatedly
for count in {1..5}
do
    runApplication setFields
    meshUpdater -overwrite
done

runApplication setFields

# decompose with constraint refinementHistory
runApplication decomposePar

# run the solver
mpirun -np 6 interDyMFoam -parallel

#------------------------------------------------------------------------------
