#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#clean case
sh cleanCase.sh

# restore 0
cp -r org/ 0

m4 constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

runApplication blockMesh

# initialize field and set refinement repeatedly (maxRefLevel+1)
for count in {1..3}
do

	echo "initialize fields and refine iteration: $c"
	setFields > log.setFields

	meshUpdater -overwrite
done

# decompose with constraint refinementHistory
runApplication decomposePar
decomposeParLevel

for i in {0..3}
do
    cp -r processor$i/0 processor$i/constant
done

#run the solver
echo "run interFoam on 4 procs"
mpirun -np 4 interFoam -parallel > log.interFoam
