#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


cleanCase()
{
	# remove logFiles
	rm -rf log*

	# remove all timeSteps but 0
	rm -rf 0.[0-9]* && rm -rf [1-9]* 

	# remove Mesh
	CASEDIR="$PWD"
	MESH="$CASEDIR/constant/polyMesh"
	if [ -d $MESH ]
	  then
	    cd "$MESH"
	    rm -rf owner*
	    rm -rf neighbour*
	    rm -rf point*
	    rm -rf face*
	    rm -rf boundary*
	    rm -rf set*
	    rm -rf cell*
	    rm -rf level0Edge*
	    rm -rf refinementHistory*
	    rm -rf surfaceIndex.gz*
	fi

	# remove Processors
	rm -rf processor*

	# restore 0
	rm -rf 0
	cp -r org/ 0
}
##############################################

cleanCase
rm -r VTK*

# case adapted dynMesh libs
cleanCase

runApplication blockMesh

initSurfaceFields

meshUpdater 

foamToVTK -surfaceFields > log.VTK

mv VTK VTK_new


# case with original OF-4-dev dynMesh libs
cleanCase
runApplication blockMesh 
 
initSurfaceFields  # ignore double linker warning!

meshUpdaterOrig  # ignore double linker warning!

foamToVTK -surfaceFields

mv VTK VTK_Orig > log.VTK