#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


#clean case
sh cleanCase.sh

# restore 0
cp -r org/ 0

runApplication blockMesh
#runApplication setSet -batch createObstacle.setSet

#runApplication topoSet
#runApplication subsetMesh -overwrite c0 -patch walls

# initialize field and set refinement repeatedly
for count in {1..3}
do

    topoSet
    subsetMesh -overwrite c0 -patch walls

    setFields
    meshUpdater -overwrite
done

runApplication setFields

# decompose with constraint refinementHistory
runApplication decomposePar

# run the solver
echo "run interDymFoam on 6 procs"
mpirun -np 6 interDyMFoam -parallel > log.interDyMFoam

#------------------------------------------------------------------------------
